# Generated by Django 3.2.25 on 2024-04-13 08:21

from django.db import migrations, models
import plant_app_revision.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=20, validators=[plant_app_revision.web.validators.starts_with_capital_letter]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=20, validators=[plant_app_revision.web.validators.starts_with_capital_letter]),
        ),
    ]
